### ISSUE TITLE
Unable to create a volume

### ISSUE THREAD

**Issue by patelrit** [profitbricks/profitbricks-sdk-java#11]
Not able to create a volume using the SDK. Periodic polling returns the status as BUSY.
Also, unit tests related to volume are failing.

Code: 
		VolumeRaw volume = new VolumeRaw();
		volume.getProperties().setName(template.getInstanceId() + " - Volume");
		volume.getProperties().setSize(String.valueOf(flavor.getStorage()));
		volume.getProperties().setLicenceType("LINUX");

		Volume newVolume = _api.getVolumeApi().createVolume(dcId, volume);

Error

16:41:17.815 [main] ERROR c.p.rest.client.RestClient - [404] Failed to send GET https://api.profitbricks.com/rest/datacenters/18a64611-2a36-4d25-8dfc-4bb335e40303/volumes/bf0eb038-9ff9-4b65-a44d-e559ae94e527?depth=5

**Comment by baldwinSPC** [comment]
@patelrit Give this one a shot: 

VolumeRaw volume = new VolumeRaw();
volume.getProperties().setName("SDK TEST VOLUME - Volume");
volume.getProperties().setSize("10");
volume.getProperties().setImage("2f5a3387-1faa-11e5-91f8-52540066fee9"); //"Ubuntu-15.04-server-2015-07-01"

Volume newVolume = profitbricksApi.getVolumeApi().createVolume(dataCenterId, volume);

Volume attachedVolume = profitbricksApi.getVolumeApi().attachVolume(dataCenterId, newServer.getId(), newVolume.getId());

Let me know if this and what I sent in email helps! I'll leave the issue open until I hear back.

**Comment by patelrit** [comment]
Works if attachVolume is called after the created volume is in RUNNING state
