### ISSUE TITLE
Setting PB-Contract-Number header

### ISSUE THREAD

**Issue by shochdoerfer** [profitbricks/profitbricks-sdk-java#28]
Currently it does not seem possible to pass the PB-Contract-Number which is needed when the to be authenticated user has access to multiple contracts.

**Comment by edevenport** [comment]
Hello @shochdoerfer - there was some discussion on whether to allow the PB-Contract-Number to be included during SDK authentication. However, we decided it probably did not make sense for security reasons.

If the contract admin credentials are ever accidentally exposed, the impact would be significant given the access it has to all resources. We decided it was a better security practice to create a contract-specific user/service account that only has access to the resources it needs. This would reduce potential exposure.

Of course, there could be other scenarios we have not considered. We would definitely like to better understand your requirements and we appreciate any feedback you might have.

**Comment by shochdoerfer** [comment]
I wasn't aware that regular users also have API access. Last time I was talking to support, I was told that only contract admin has API access (but that might refer to the Billing API as we only used that API in the past). Works for me then. Thanks!
